![giskard_logo.png](https://raw.githubusercontent.com/Giskard-AI/giskard/main/readme/Logo_full_darkgreen.png)

# About Giskard

Open-Source CI/CD platform for ML teams. Deliver ML products, better & faster. 

*   Collaborate faster with feedback from business stakeholders.
*   Deploy automated tests to eliminate regressions, errors & biases.

🏡 [Website](https://giskard.ai/)

📗 [Documentation](https://docs.giskard.ai/)

# Start by creating a ML model 🚀🚀🚀

Download the categorized email files from Berkeley.

In [3]:
!wget http://bailando.sims.berkeley.edu/enron/enron_with_categories.tar.gz
!tar zxf enron_with_categories.tar.gz
!rm enron_with_categories.tar.gz

--2022-08-09 23:22:34--  http://bailando.sims.berkeley.edu/enron/enron_with_categories.tar.gz
Resolving bailando.sims.berkeley.edu (bailando.sims.berkeley.edu)... 128.32.78.19
Connecting to bailando.sims.berkeley.edu (bailando.sims.berkeley.edu)|128.32.78.19|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://bailando.berkeley.edu/enron/enron_with_categories.tar.gz [following]
--2022-08-09 23:22:35--  https://bailando.berkeley.edu/enron/enron_with_categories.tar.gz
Resolving bailando.berkeley.edu (bailando.berkeley.edu)... 128.32.78.19
Connecting to bailando.berkeley.edu (bailando.berkeley.edu)|128.32.78.19|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4523350 (4.3M) [application/x-gzip]
Saving to: ‘enron_with_categories.tar.gz’

enron_with_categori 100%[===================>]   4.31M  2.56MB/s    in 1.7s    

2022-08-09 23:22:38 (2.56 MB/s) - ‘enron_with_categories.tar.gz’ saved [4523350/4523350]



In [4]:
!pip install transformers


[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip


In [5]:
!pip install torch


[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip


In [6]:
!pip install nltk


[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip


In [7]:
!pip install giskard


[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip


In [8]:
import email
import glob

from collections import defaultdict

import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from string import punctuation

import pandas as pd
from dateutil import parser
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer


from sklearn.linear_model import LogisticRegression
from sklearn import model_selection

Various imports and the list of categories from http://bailando.sims.berkeley.edu/enron/enron_categories.txt.

In [9]:
nltk.download('punkt')
nltk.download('stopwords')

stoplist = set(stopwords.words('english') + list(punctuation))
stemmer = PorterStemmer()


# http://bailando.sims.berkeley.edu/enron/enron_categories.txt
idx_to_cat = {
    1: 'REGULATION',
    2: 'INTERNAL',
    3: 'INFLUENCE',
    4: 'INFLUENCE',
    5: 'INFLUENCE',
    6: 'CALIFORNIA CRISIS',
    7: 'INTERNAL',
    8: 'INTERNAL',
    9: 'INFLUENCE',
    10: 'REGULATION',
    11: 'talking points',
    12: 'meeting minutes',
    13: 'trip reports'}

idx_to_cat2 = {
    1: 'regulations and regulators (includes price caps)',
    2: 'internal projects -- progress and strategy',
    3: ' company image -- current',
    4: 'company image -- changing / influencing',
    5: 'political influence / contributions / contacts',
    6: 'california energy crisis / california politics',
    7: 'internal company policy',
    8: 'internal company operations',
    9: 'alliances / partnerships',
    10: 'legal advice',
    11: 'talking points',
    12: 'meeting minutes',
    13: 'trip reports'}


LABEL_CAT = 3  # we'll be using the 2nd-level category "Primary topics" because the two first levels provide categories that are not mutually exclusive. see : https://bailando.berkeley.edu/enron/enron_categories.txt

#get_labels returns a dictionary representation of these labels. 
def get_labels(filename):
    with open(filename + '.cats') as f:
        labels = defaultdict(dict)
        line = f.readline()
        while line:
            line = line.split(',')
            top_cat, sub_cat, freq = int(line[0]), int(line[1]), int(line[2])
            labels[top_cat][sub_cat] = freq
            line = f.readline()
    return dict(labels)


email_files = [f.replace('.cats', '') for f in glob.glob('enron_with_categories/*/*.cats')]

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/andreyavtomonov/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/andreyavtomonov/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


##Build dataframe

In [10]:
columns_name = ['Target', 'Subject', 'Content', 'Week_day', 'Year', 'Month', 'Hour', 'Nb_of_forwarded_msg']


data = pd.DataFrame(columns=columns_name)

for email_file in email_files:
    values_to_add = {}

    #Target is the sub-category with maximum frequency
    if LABEL_CAT in get_labels(email_file):
      sub_cat_dict = get_labels(email_file)[LABEL_CAT]
      target_int = max(sub_cat_dict, key=sub_cat_dict.get)
      values_to_add['Target'] = str(idx_to_cat[target_int])

    #Features are metadata from the email object
    filename = email_file+'.txt'
    with open(filename) as f:

      message = email.message_from_string(f.read())
  
      values_to_add['Subject'] = str(message['Subject'])
      values_to_add['Content'] = str(message.get_payload())
     
      date_time_obj = parser.parse(message['Date'])
      values_to_add['Week_day'] = date_time_obj.strftime("%A")
      values_to_add['Year'] = date_time_obj.strftime("%Y")
      values_to_add['Month'] = date_time_obj.strftime("%B")
      values_to_add['Hour'] = int(date_time_obj.strftime("%H"))

      # Count number of forwarded mails
      number_of_messages = 0
      for line in message.get_payload().split('\n'):
        if ('forwarded' in line.lower() or 'original' in line.lower()) and '--' in line:
            number_of_messages += 1
      values_to_add['Nb_of_forwarded_msg'] = number_of_messages
    
    row_to_add = pd.Series(values_to_add)
    data = data.append(row_to_add, ignore_index=True)

Filter Dataframe

In [11]:
#We filter 879 rows (if Primary topics exists (i.e. if coarse genre 1.1 is selected) )
data_filtered = data[data["Target"].notnull()]

#Exclude target category with very few rows ; 812 rows remains
excluded_category = [idx_to_cat[i] for i in [11,12,13]]
data_filtered = data_filtered[data_filtered["Target"].isin(excluded_category) == False]
num_classes = len(data_filtered["Target"].value_counts())

In [12]:
column_types={       
        'Target': "category",
        "Subject": "text",
        "Content": "text",
        "Week_day": "category",
        "Month": "category",
        "Hour": "numeric",
        "Nb_of_forwarded_msg": "numeric",
        "Year": "numeric"
    }

Training with scikit learn pipeline

In [13]:
feature_types = {i:column_types[i] for i in column_types if i!='Target'}

columns_to_scale = [key for key in feature_types.keys() if feature_types[key]=="numeric"]

numeric_transformer = Pipeline([('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())])


columns_to_encode = [key for key in feature_types.keys() if feature_types[key]=="category"]

categorical_transformer = Pipeline([
        ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
        ('onehot', OneHotEncoder(handle_unknown='ignore',sparse=False)) ])
text_transformer = Pipeline([
                      ('vect', CountVectorizer(stop_words=stoplist)),
                      ('tfidf', TfidfTransformer())
                     ])
preprocessor = ColumnTransformer(
    transformers=[
      ('num', numeric_transformer, columns_to_scale),
      ('cat', categorical_transformer, columns_to_encode),
      ('text_Mail', text_transformer, "Content")
    ]
)
clf = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', LogisticRegression(max_iter =1000))])

Split train/test

In [14]:
feature_types = {i:column_types[i] for i in column_types if i!="Target"}
Y = data_filtered["Target"]
X = data_filtered.drop(columns=["Target"])
X_train,X_test,Y_train,Y_test = model_selection.train_test_split(X, Y,test_size=0.20, random_state = 30, stratify = Y)

Learning phase

In [15]:
clf.fit(X_train, Y_train)
print("model score: %.3f" % clf.score(X_test, Y_test))

model score: 0.500


In [16]:
train_data = pd.concat([X_train, Y_train], axis=1)
test_data = pd.concat([X_test, Y_test ], axis=1)

#Upload the model in Giskard 🚀🚀🚀

### Initiate a project


In [28]:
from giskard.giskard_client import GiskardClient

url = "http://localhost:9000" # if docker image is running on your local
#url = "http://app.giskard.ai" # If you want to upload on giskard URL 
token = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwiaWQiOjQsInRva2VuX3R5cGUiOiJVSSIsImV4cCI6MTY2MDEyMTQ5NX0.dqdyTtFbL71VN18QsZFGz2Ph3-lDHoV1ouzfZT2cSLU" #you can generate your API token in the Admin tab of the Giskard application (for installation, see: https://docs.giskard.ai/start/guides/installation)

client = GiskardClient(url, token)

# enron = client.create_project("enron_demo", "Enron Mails Classification", "Project to classify enron mails")

#If you've already created a project with the key "enron_demo" use
enron = client.get_project("enron_demo")

### Upload your model and a dataset (see [documentation](https://docs.giskard.ai/start/guides/upload-your-model))

In [ ]:
enron.upload_model_and_df(
    prediction_function=clf.predict_proba, 
    model_type='classification',
    df=test_data, #the dataset you want to use to inspect your model
    column_types=column_types, #all the column types of df
    target='Target', #the column name in df corresponding to the actual target variable (ground truth).
    feature_names=list(feature_types.keys()),#list of the feature names of prediction_function
    model_name='logistic_regression_model',
    dataset_name='test_data',
    classification_labels=clf.classes_
)

### 🌟 If you want to upload a dataset without a model


For example, let's upload the train set in Giskard, this is key to create drift tests in Giskard.

In [ ]:
enron.upload_df(
    df=train_data,
    column_types=column_types, #all the column types of df
    target="Target", # do not pass this parameter if dataset doesnt contain target column 
    name="train_data"
)

You can also upload new production data to use it as a validatation set for your existing model. In that case, you might not have the ground truth target variable

In [ ]:
production_data = data.drop(columns="Target")


In [ ]:
enron.upload_df(
    df=production_data,
    column_types=feature_types, #all the column types without the target
    name="production_data"
)

### 🌟 If you just want to upload a model without a dataframe
#### Lets try a Hugging Face pytorch model

In [17]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
import torch
from transformers import TrainingArguments, Trainer
from transformers import BertTokenizer, BertForSequenceClassification

np.random.seed(112)

# Read data
data = data_filtered

# Define pretrained tokenizer and model
# model_name = "bert-base-uncased" # For large BERT Model
model_name = "cross-encoder/ms-marco-TinyBERT-L-2" # For tiny BERT Model

tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertForSequenceClassification.from_pretrained(model_name, num_labels=4, ignore_mismatched_sizes=True)

for param in model.base_model.parameters():
    param.requires_grad = False

# ----- 1. Preprocess data -----#
# Preprocess data

X = list(data["Content"])
classification_labels_mapping = {'REGULATION': 0,'INTERNAL': 1,'CALIFORNIA CRISIS': 2,'INFLUENCE': 3}
y = list(data_filtered['Target'].map(classification_labels_mapping))

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)
X_train_tokenized = tokenizer(X_train, padding=True, truncation=True, max_length=128)
X_val_tokenized = tokenizer(X_val, padding=True, truncation=True, max_length=128)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cross-encoder/ms-marco-TinyBERT-L-2 and are newly initialized because the shapes did not match:
- classifier.weight: found shape torch.Size([1, 128]) in the checkpoint and torch.Size([4, 128]) in the model instantiated
- classifier.bias: found shape torch.Size([1]) in the checkpoint and torch.Size([4]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [18]:
# Create torch dataset
class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        if self.labels:
            item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.encodings["input_ids"])

train_dataset = Dataset(X_train_tokenized, y_train)
val_dataset = Dataset(X_val_tokenized, y_val)

# ----- 2. Fine-tune pretrained model -----#
# Define Trainer parameters
def compute_metrics(p):
    pred, labels = p
    pred = np.argmax(pred, axis=1)

    accuracy = accuracy_score(y_true=labels, y_pred=pred)
    recall = recall_score(y_true=labels, y_pred=pred, average='macro')
    precision = precision_score(y_true=labels, y_pred=pred, average='macro')
    f1 = f1_score(y_true=labels, y_pred=pred, average='macro')

    return {"accuracy": accuracy, "precision": precision, "recall": recall, "f1": f1}



In [19]:
# Define Trainer
args = TrainingArguments(
    output_dir="output",
    evaluation_strategy="steps",
    eval_steps=500,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=1,
    seed=0,
    load_best_model_at_end=True,
)
trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
    )

# Train pre-trained model
trainer.train()

/Users/andreyavtomonov/projects/work/giskard-notebooks/.venv/lib/python3.7/site-packages/transformers/optimization.py:310: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,
***** Running training *****
  Num examples = 679
  Num Epochs = 1
  Instantaneous batch size per device = 8
  Total train batch size (w. parallel, distributed & accumulation) = 8
  Gradient Accumulation steps = 1
  Total optimization steps = 85




Training completed. Do not forget to share your model on huggingface.co/models =)




TrainOutput(global_step=85, training_loss=1.434090378705193, metrics={'train_runtime': 18.9342, 'train_samples_per_second': 35.861, 'train_steps_per_second': 4.489, 'total_flos': 215799714816.0, 'train_loss': 1.434090378705193, 'epoch': 1.0})

In [20]:
trainer.evaluate()

***** Running Evaluation *****
  Num examples = 170
  Batch size = 8


/Users/andreyavtomonov/projects/work/giskard-notebooks/.venv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


{'eval_loss': 1.4226306676864624,
 'eval_accuracy': 0.2411764705882353,
 'eval_precision': 0.060294117647058824,
 'eval_recall': 0.25,
 'eval_f1': 0.0971563981042654,
 'eval_runtime': 3.0421,
 'eval_samples_per_second': 55.882,
 'eval_steps_per_second': 7.232,
 'epoch': 1.0}

In [21]:
def predict(test_dataset):
    test_dataset= test_dataset.squeeze() if len(test_dataset) >1 else test_dataset
    X_test = list(test_dataset)
    X_test_tokenized = tokenizer(X_test, padding=True, truncation=True, max_length=512)

    # Create torch dataset
    test_dataset = Dataset(X_test_tokenized)

    # Define test trainer
    test_trainer = Trainer(model)

    # Make prediction
    raw_pred, _, _ = test_trainer.predict(test_dataset)
    predictions = torch.nn.functional.softmax(torch.from_numpy(raw_pred), dim=-1)
    predictions = predictions.cpu().detach().numpy()

    return predictions

In [24]:
columns = ['Content']
data = data_filtered[columns]
predictions = predict(data)
print("Data shape", data.shape)
print("Predictions shape", predictions.shape)
print("Predictions", predictions)

No `TrainingArguments` passed, using `output_dir=tmp_trainer`.
PyTorch: setting up devices
The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).
***** Running Prediction *****
  Num examples = 849
  Batch size = 8


Data shape (849, 1)
Predictions shape (849, 4)
Predictions [[0.18490693 0.25284272 0.22204557 0.34020486]
 [0.23501915 0.26979828 0.16072588 0.33445665]
 [0.21871668 0.23186392 0.1901572  0.35926217]
 ...
 [0.21175483 0.18573262 0.21003544 0.39247712]
 [0.2164718  0.24685013 0.19512649 0.34155157]
 [0.21720079 0.22475062 0.19288997 0.3651586 ]]


In [25]:
feature_names = ['Content']
test_df = data_filtered[feature_names][:5]
predict(test_df)

No `TrainingArguments` passed, using `output_dir=tmp_trainer`.
PyTorch: setting up devices
The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).
***** Running Prediction *****
  Num examples = 5
  Batch size = 8


array([[0.1849069 , 0.2528427 , 0.22204557, 0.34020483],
       [0.23501916, 0.26979828, 0.16072588, 0.33445665],
       [0.21871668, 0.23186392, 0.19015718, 0.35926217],
       [0.21776284, 0.25436628, 0.17266421, 0.3552067 ],
       [0.21825351, 0.25387916, 0.2024011 , 0.32546628]], dtype=float32)

In [29]:
enron.upload_model(
    prediction_function=predict, 
    model_type='classification',
    validate_df=data_filtered.head(), #Optional. Validation df is not uploaded in the app, it's only used to check whether the model has the good format
    target='Target',
    feature_names=feature_names,#list of the feature names of prediction_function
    name='bert_pytorch_model',
    classification_labels=list(classification_labels_mapping.keys())
)

No `TrainingArguments` passed, using `output_dir=tmp_trainer`.
PyTorch: setting up devices
The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).
***** Running Prediction *****
  Num examples = 5
  Batch size = 8


Model successfully uploaded to project key 'enron_demo' and is available at http://localhost:9000 
